### ISSUE TITLE
'SDCARD_SS_PIN' was not declared in this scope

### ISSUE THREAD

**Issue by phunanon** [technoblogy/ulisp-serpente#1]
Uncommenting `sdcardsupport` with [serpente-core](https://github.com/technoblogy/serpente-core/) installed:

`'SDCARD_SS_PIN' was not declared in this scope`

**Comment by technoblogy** [comment]
You need to add a #define such as:

    #define SDCARD_SS_PIN 4

to specify which pin you're using for select.

**Comment by phunanon** [comment]
@technoblogy, I tried this in the Arduino SD card info example, which also didn't work, and booting uLisp and evaluating `(save-image)` gave:  
`Error: 'save-image' problem saving to SD card`

For clarity, this is the R2 version, which is mounting correctly as a USB device on my machine. I haven't tried it for CircuitPython stuff though.

**Comment by technoblogy** [comment]
How are you connecting an SD card to the Serpente board?

**Comment by phunanon** [comment]
Ah, I apologise greatly. I didn't realise that SD support and *flash* support were two different concepts - I'm new to the device and thought it was an emulated SD 4MB card through SPI or something.

It might be a nice idea to include the Flash code as a separate reusable library, but I'm not so aware on how uLisp is implemented across platforms.

Thank you for your time! 😅

**Comment by phunanon** [comment]
Never mind again... https://github.com/technoblogy/simple-dataflash

**Comment by technoblogy** [comment]
You're welcome!
